//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصدار البرنامج.
        /// </summary>
        public static string AppVersionNumber {
            get {
                return ResourceManager.GetString("AppVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير الاعدادات يتطلب اعاده تشغيل البرنامج.
        /// </summary>
        public static string ChangeLanguageSettingsWarningMSG {
            get {
                return ResourceManager.GetString("ChangeLanguageSettingsWarningMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحقق من وجود تحديثات.
        /// </summary>
        public static string CheckForUpdatesText {
            get {
                return ResourceManager.GetString("CheckForUpdatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسود.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قاعدة البيانات: .
        /// </summary>
        public static string DatabaseNameMainPage {
            get {
                return ResourceManager.GetString("DatabaseNameMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حمل التحديث.
        /// </summary>
        public static string DownloadUpdateText {
            get {
                return ResourceManager.GetString("DownloadUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاتصال.
        /// </summary>
        public static string FirstRunTitle {
            get {
                return ResourceManager.GetString("FirstRunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابيض.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدعم الفنى المباشر.
        /// </summary>
        public static string LiveSupportChat {
            get {
                return ResourceManager.GetString("LiveSupportChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ايزى ستور.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرنامج يعمل بالفعل.
        /// </summary>
        public static string ProgramRunning {
            get {
                return ResourceManager.GetString("ProgramRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيرفر: متصل.
        /// </summary>
        public static string RemoteServerStatusConnected {
            get {
                return ResourceManager.GetString("RemoteServerStatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيرفر: غير مضاف.
        /// </summary>
        public static string RemoteServerStatusNotAdded {
            get {
                return ResourceManager.GetString("RemoteServerStatusNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيرفر: غير متاح.
        /// </summary>
        public static string RemoteServerStatusNotConnected {
            get {
                return ResourceManager.GetString("RemoteServerStatusNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختار اللون.
        /// </summary>
        public static string SettingsColorSelect {
            get {
                return ResourceManager.GetString("SettingsColorSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخضر.
        /// </summary>
        public static string SettingsColorWatermark {
            get {
                return ResourceManager.GetString("SettingsColorWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربى (Arabic).
        /// </summary>
        public static string SettingsLanguageArabicItem {
            get {
                return ResourceManager.GetString("SettingsLanguageArabicItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجليزى (English).
        /// </summary>
        public static string SettingsLanguageEnglishItem {
            get {
                return ResourceManager.GetString("SettingsLanguageEnglishItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختار اللغة.
        /// </summary>
        public static string SettingsLanguageSelect {
            get {
                return ResourceManager.GetString("SettingsLanguageSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربى / انجليزى.
        /// </summary>
        public static string SettingsLanguageWatermark {
            get {
                return ResourceManager.GetString("SettingsLanguageWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختار الثيم.
        /// </summary>
        public static string SettingsThemeSelect {
            get {
                return ResourceManager.GetString("SettingsThemeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابيض / اسود.
        /// </summary>
        public static string SettingsThemeWatermark {
            get {
                return ResourceManager.GetString("SettingsThemeWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعدادات.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير معروف.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحذير.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
